### PR TITLE
Roles

### PR DESCRIPTION
**Pull request by skbt27i**

### CODE REVIEW

**Comment by awhigham9** [comment]
The `roles` set will have to be populated at startup with the rolls in the server. This will need some kind of call to `client.guild`.

Also, you could have it refresh the `roles` set when `rolls` is called.

**Comment by awhigham9** [comment]
Also, rather than using a special role called `'Officer'` as the privileged user, we should use the server admin as the privileged user, probably

**Comment by skbt27i** [comment]
make sure to not /openrole offircer

**Review by awhigham9 — APPROVED** [review]
Looks good. Local tests work. Not worried about code style, as the lint issue will patch any of that later.

**Pull request merged**
