### PR TITLE
Awhigham9/add polling

### PR DESCRIPTION
**Pull request by awhigham9**
Add a MVP set of commands for running polls. 

Polls only support 1 question currently, though code has features for multi-question polls later. Each poll is assigned an integer id at creation. Polls are stored in-memory and erased at bot shutdown.

Adds 5 commands:

## `/startpoll`
Creates a new poll. The poll starts "open", meaning it can be voted on.

Args:
+ `pollname`: name of the poll
+ `question`: string capturing the polls question
+ `choices`: string capturing the question's choices delimited by `|`

## `/polls`
Lists polls and their IDs, both closed and open. Closed polls have an asterisk to mark them as such.

## `/seepoll`
View a poll. Shows name, question, options, and current votes for each option.

Args:
+ `pollid`: ID of the poll (can be found with `/polls`)

## `/closepoll`
Close a poll to stop new votes.

Args:
+ `pollid`: ID of the poll (can be found with `/polls`)

## `/vote`
Vote on a poll. 

Args:
+ `pollid`: ID of the poll (can be found with `/polls`)
+ `choices`: Choices for each question of the poll, expressed as number (e.g. `1` means the first option). Support for multiple questions exists, by having numbers delimited by `|`. This is unused currently.

### CODE REVIEW

**Comment by awhigham9** [comment]
@skbt27i Would you mind pulling this and giving it a test when you get a chance? For functionality but more importantly ease of use. Let me know if you have any feedback. Thanks!

**Comment by awhigham9** [comment]
Addresses #3

**Comment by awhigham9** [comment]
I think it might be that [line 280](https://github.com/ufosc/ALBot-2.0/blob/45319324b1ac9573a561c8445be75386af6d6053/src/commands/poll.ts#L280) needs to be followed be a `return;`.

I'll try to repro and then try this fix out

**Comment by awhigham9** [comment]
I managed to repro the bug by voting with a bad choices string: `/vote pollid: 0 choices: this is not a number`.

After adding `return` after line 280 as discussed, the bug stopped occurring. I think this was indeed the root cause. Also, I added `return;` after each `interaction.reply` to prevent this kind of error occurring.

See most recent commit.

**Comment by awhigham9** [comment]
@skbt27i Can you review with bug fix applied?

**Comment by skbt27i** [comment]
looks good

**Review by skbt27i — APPROVED** [review]

**Pull request merged**
