### PR TITLE
Hello world

### PR DESCRIPTION
**Pull request by skbt27i**

### CODE REVIEW

**Comment by skbt27i** [comment]
Looks mostly good, but could you make the programming language the user input case insensitive

**Comment by awhigham9** [comment]
Nitpick: Can you change the name of `hello_world.ts` to `helloWorld.ts`?

We are aiming to use camel case for all the files, though some of the older ones are still wrong

**Comment by awhigham9** [comment]
Nitpick: Can you change the name of the command `helloworld_list` to `helloworld-list` to match the other commands using dashes?

**Comment by awhigham9** [comment]
Why does this PR think the code for the project command is included? Is GitHub not resolving the diff to main correctly?

Any idea @skbt27i?

**Review by awhigham9 — CHANGES_REQUESTED** [review]
See previous comments and skbti27's comments.

Looks good otherwise, and good work keeping the implementation straightforward and efficient.

**Comment by skbt27i** [comment]
> Why does this PR think the code for the project command is included? Is GitHub not resolving the diff to main correctly?
> 
> Any idea @skbt27i?

Not sure, let's see what it does when merging?

**Comment by devp4** [comment]
Done!

**Pull request merged**
